// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package atendindividual

import (
	"br/gov/saude/esusab/ras/common"
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = common.GoUnusedProtection__
var GoUnusedProtection__ int

type OutrosSiaThrift struct {
	CodigoExame        *string  `thrift:"codigoExame,1" json:"codigoExame"`
	SolicitadoAvaliado []string `thrift:"solicitadoAvaliado,2" json:"solicitadoAvaliado"`
}

func NewOutrosSiaThrift() *OutrosSiaThrift {
	return &OutrosSiaThrift{}
}

var OutrosSiaThrift_CodigoExame_DEFAULT string

func (p *OutrosSiaThrift) GetCodigoExame() string {
	if !p.IsSetCodigoExame() {
		return OutrosSiaThrift_CodigoExame_DEFAULT
	}
	return *p.CodigoExame
}

var OutrosSiaThrift_SolicitadoAvaliado_DEFAULT []string

func (p *OutrosSiaThrift) GetSolicitadoAvaliado() []string {
	return p.SolicitadoAvaliado
}
func (p *OutrosSiaThrift) IsSetCodigoExame() bool {
	return p.CodigoExame != nil
}

func (p *OutrosSiaThrift) IsSetSolicitadoAvaliado() bool {
	return p.SolicitadoAvaliado != nil
}

func (p *OutrosSiaThrift) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *OutrosSiaThrift) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.CodigoExame = &v
	}
	return nil
}

func (p *OutrosSiaThrift) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]string, 0, size)
	p.SolicitadoAvaliado = tSlice
	for i := 0; i < size; i++ {
		var _elem0 string
		if v, err := iprot.ReadString(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem0 = v
		}
		p.SolicitadoAvaliado = append(p.SolicitadoAvaliado, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *OutrosSiaThrift) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("OutrosSiaThrift"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *OutrosSiaThrift) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetCodigoExame() {
		if err := oprot.WriteFieldBegin("codigoExame", thrift.STRING, 1); err != nil {
			return fmt.Errorf("%T write field begin error 1:codigoExame: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.CodigoExame)); err != nil {
			return fmt.Errorf("%T.codigoExame (1) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 1:codigoExame: %s", p, err)
		}
	}
	return err
}

func (p *OutrosSiaThrift) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetSolicitadoAvaliado() {
		if err := oprot.WriteFieldBegin("solicitadoAvaliado", thrift.LIST, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:solicitadoAvaliado: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.SolicitadoAvaliado)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.SolicitadoAvaliado {
			if err := oprot.WriteString(string(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:solicitadoAvaliado: %s", p, err)
		}
	}
	return err
}

func (p *OutrosSiaThrift) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OutrosSiaThrift(%+v)", *p)
}

type ProblemaCondicaoAvaliacaoAIThrift struct {
	Ciaps      []string `thrift:"ciaps,1" json:"ciaps"`
	OutroCiap1 *string  `thrift:"outroCiap1,2" json:"outroCiap1"`
	OutroCiap2 *string  `thrift:"outroCiap2,3" json:"outroCiap2"`
	Cid10      *string  `thrift:"cid10,4" json:"cid10"`
	Cid10_2    *string  `thrift:"cid10_2,5" json:"cid10_2"`
}

func NewProblemaCondicaoAvaliacaoAIThrift() *ProblemaCondicaoAvaliacaoAIThrift {
	return &ProblemaCondicaoAvaliacaoAIThrift{}
}

var ProblemaCondicaoAvaliacaoAIThrift_Ciaps_DEFAULT []string

func (p *ProblemaCondicaoAvaliacaoAIThrift) GetCiaps() []string {
	return p.Ciaps
}

var ProblemaCondicaoAvaliacaoAIThrift_OutroCiap1_DEFAULT string

func (p *ProblemaCondicaoAvaliacaoAIThrift) GetOutroCiap1() string {
	if !p.IsSetOutroCiap1() {
		return ProblemaCondicaoAvaliacaoAIThrift_OutroCiap1_DEFAULT
	}
	return *p.OutroCiap1
}

var ProblemaCondicaoAvaliacaoAIThrift_OutroCiap2_DEFAULT string

func (p *ProblemaCondicaoAvaliacaoAIThrift) GetOutroCiap2() string {
	if !p.IsSetOutroCiap2() {
		return ProblemaCondicaoAvaliacaoAIThrift_OutroCiap2_DEFAULT
	}
	return *p.OutroCiap2
}

var ProblemaCondicaoAvaliacaoAIThrift_Cid10_DEFAULT string

func (p *ProblemaCondicaoAvaliacaoAIThrift) GetCid10() string {
	if !p.IsSetCid10() {
		return ProblemaCondicaoAvaliacaoAIThrift_Cid10_DEFAULT
	}
	return *p.Cid10
}

var ProblemaCondicaoAvaliacaoAIThrift_Cid10_2_DEFAULT string

func (p *ProblemaCondicaoAvaliacaoAIThrift) GetCid10_2() string {
	if !p.IsSetCid10_2() {
		return ProblemaCondicaoAvaliacaoAIThrift_Cid10_2_DEFAULT
	}
	return *p.Cid10_2
}
func (p *ProblemaCondicaoAvaliacaoAIThrift) IsSetCiaps() bool {
	return p.Ciaps != nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) IsSetOutroCiap1() bool {
	return p.OutroCiap1 != nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) IsSetOutroCiap2() bool {
	return p.OutroCiap2 != nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) IsSetCid10() bool {
	return p.Cid10 != nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) IsSetCid10_2() bool {
	return p.Cid10_2 != nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]string, 0, size)
	p.Ciaps = tSlice
	for i := 0; i < size; i++ {
		var _elem1 string
		if v, err := iprot.ReadString(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem1 = v
		}
		p.Ciaps = append(p.Ciaps, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.OutroCiap1 = &v
	}
	return nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.OutroCiap2 = &v
	}
	return nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.Cid10 = &v
	}
	return nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.Cid10_2 = &v
	}
	return nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ProblemaCondicaoAvaliacaoAIThrift"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetCiaps() {
		if err := oprot.WriteFieldBegin("ciaps", thrift.LIST, 1); err != nil {
			return fmt.Errorf("%T write field begin error 1:ciaps: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.Ciaps)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.Ciaps {
			if err := oprot.WriteString(string(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 1:ciaps: %s", p, err)
		}
	}
	return err
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetOutroCiap1() {
		if err := oprot.WriteFieldBegin("outroCiap1", thrift.STRING, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:outroCiap1: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.OutroCiap1)); err != nil {
			return fmt.Errorf("%T.outroCiap1 (2) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:outroCiap1: %s", p, err)
		}
	}
	return err
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetOutroCiap2() {
		if err := oprot.WriteFieldBegin("outroCiap2", thrift.STRING, 3); err != nil {
			return fmt.Errorf("%T write field begin error 3:outroCiap2: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.OutroCiap2)); err != nil {
			return fmt.Errorf("%T.outroCiap2 (3) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 3:outroCiap2: %s", p, err)
		}
	}
	return err
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCid10() {
		if err := oprot.WriteFieldBegin("cid10", thrift.STRING, 4); err != nil {
			return fmt.Errorf("%T write field begin error 4:cid10: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.Cid10)); err != nil {
			return fmt.Errorf("%T.cid10 (4) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 4:cid10: %s", p, err)
		}
	}
	return err
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetCid10_2() {
		if err := oprot.WriteFieldBegin("cid10_2", thrift.STRING, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:cid10_2: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.Cid10_2)); err != nil {
			return fmt.Errorf("%T.cid10_2 (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:cid10_2: %s", p, err)
		}
	}
	return err
}

func (p *ProblemaCondicaoAvaliacaoAIThrift) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProblemaCondicaoAvaliacaoAIThrift(%+v)", *p)
}

type FichaAtendimentoIndividualChildThrift struct {
	NumeroProntuario                *string                            `thrift:"numeroProntuario,1" json:"numeroProntuario"`
	Cns                             *string                            `thrift:"cns,2" json:"cns"`
	DataNascimento                  *int64                             `thrift:"dataNascimento,3" json:"dataNascimento"`
	LocalDeAtendimento              *int64                             `thrift:"localDeAtendimento,4" json:"localDeAtendimento"`
	Sexo                            *int64                             `thrift:"sexo,5" json:"sexo"`
	Turno                           *int64                             `thrift:"turno,6" json:"turno"`
	TipoAtendimento                 *int64                             `thrift:"tipoAtendimento,7" json:"tipoAtendimento"`
	PesoAcompanhamentoNutricional   *float64                           `thrift:"pesoAcompanhamentoNutricional,8" json:"pesoAcompanhamentoNutricional"`
	AlturaAcompanhamentoNutricional *float64                           `thrift:"alturaAcompanhamentoNutricional,9" json:"alturaAcompanhamentoNutricional"`
	AleitamentoMaterno              *int64                             `thrift:"aleitamentoMaterno,10" json:"aleitamentoMaterno"`
	DumDaGestante                   *int64                             `thrift:"dumDaGestante,11" json:"dumDaGestante"`
	IdadeGestacional                *int32                             `thrift:"idadeGestacional,12" json:"idadeGestacional"`
	AtencaoDomiciliarModalidade     *int64                             `thrift:"atencaoDomiciliarModalidade,13" json:"atencaoDomiciliarModalidade"`
	ProblemaCondicaoAvaliada        *ProblemaCondicaoAvaliacaoAIThrift `thrift:"problemaCondicaoAvaliada,14" json:"problemaCondicaoAvaliada"`
	ExamesSolicitados               []string                           `thrift:"examesSolicitados,15" json:"examesSolicitados"`
	ExamesAvaliados                 []string                           `thrift:"examesAvaliados,16" json:"examesAvaliados"`
	OutrosSia                       []*OutrosSiaThrift                 `thrift:"outrosSia,17" json:"outrosSia"`
	VacinaEmDia                     *bool                              `thrift:"vacinaEmDia,18" json:"vacinaEmDia"`
	Pic                             *int64                             `thrift:"pic,19" json:"pic"`
	FicouEmObservacao               *bool                              `thrift:"ficouEmObservacao,20" json:"ficouEmObservacao"`
	Nasfs                           []int64                            `thrift:"nasfs,21" json:"nasfs"`
	Condutas                        []int64                            `thrift:"condutas,22" json:"condutas"`
	StGravidezPlanejada             *bool                              `thrift:"stGravidezPlanejada,23" json:"stGravidezPlanejada"`
	NuGestasPrevias                 *int32                             `thrift:"nuGestasPrevias,24" json:"nuGestasPrevias"`
	NuPartos                        *int32                             `thrift:"nuPartos,25" json:"nuPartos"`
	RacionalidadeSaude              *int64                             `thrift:"racionalidadeSaude,26" json:"racionalidadeSaude"`
	PerimetroCefalico               *float64                           `thrift:"perimetroCefalico,27" json:"perimetroCefalico"`
}

func NewFichaAtendimentoIndividualChildThrift() *FichaAtendimentoIndividualChildThrift {
	return &FichaAtendimentoIndividualChildThrift{}
}

var FichaAtendimentoIndividualChildThrift_NumeroProntuario_DEFAULT string

func (p *FichaAtendimentoIndividualChildThrift) GetNumeroProntuario() string {
	if !p.IsSetNumeroProntuario() {
		return FichaAtendimentoIndividualChildThrift_NumeroProntuario_DEFAULT
	}
	return *p.NumeroProntuario
}

var FichaAtendimentoIndividualChildThrift_Cns_DEFAULT string

func (p *FichaAtendimentoIndividualChildThrift) GetCns() string {
	if !p.IsSetCns() {
		return FichaAtendimentoIndividualChildThrift_Cns_DEFAULT
	}
	return *p.Cns
}

var FichaAtendimentoIndividualChildThrift_DataNascimento_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetDataNascimento() int64 {
	if !p.IsSetDataNascimento() {
		return FichaAtendimentoIndividualChildThrift_DataNascimento_DEFAULT
	}
	return *p.DataNascimento
}

var FichaAtendimentoIndividualChildThrift_LocalDeAtendimento_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetLocalDeAtendimento() int64 {
	if !p.IsSetLocalDeAtendimento() {
		return FichaAtendimentoIndividualChildThrift_LocalDeAtendimento_DEFAULT
	}
	return *p.LocalDeAtendimento
}

var FichaAtendimentoIndividualChildThrift_Sexo_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetSexo() int64 {
	if !p.IsSetSexo() {
		return FichaAtendimentoIndividualChildThrift_Sexo_DEFAULT
	}
	return *p.Sexo
}

var FichaAtendimentoIndividualChildThrift_Turno_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetTurno() int64 {
	if !p.IsSetTurno() {
		return FichaAtendimentoIndividualChildThrift_Turno_DEFAULT
	}
	return *p.Turno
}

var FichaAtendimentoIndividualChildThrift_TipoAtendimento_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetTipoAtendimento() int64 {
	if !p.IsSetTipoAtendimento() {
		return FichaAtendimentoIndividualChildThrift_TipoAtendimento_DEFAULT
	}
	return *p.TipoAtendimento
}

var FichaAtendimentoIndividualChildThrift_PesoAcompanhamentoNutricional_DEFAULT float64

func (p *FichaAtendimentoIndividualChildThrift) GetPesoAcompanhamentoNutricional() float64 {
	if !p.IsSetPesoAcompanhamentoNutricional() {
		return FichaAtendimentoIndividualChildThrift_PesoAcompanhamentoNutricional_DEFAULT
	}
	return *p.PesoAcompanhamentoNutricional
}

var FichaAtendimentoIndividualChildThrift_AlturaAcompanhamentoNutricional_DEFAULT float64

func (p *FichaAtendimentoIndividualChildThrift) GetAlturaAcompanhamentoNutricional() float64 {
	if !p.IsSetAlturaAcompanhamentoNutricional() {
		return FichaAtendimentoIndividualChildThrift_AlturaAcompanhamentoNutricional_DEFAULT
	}
	return *p.AlturaAcompanhamentoNutricional
}

var FichaAtendimentoIndividualChildThrift_AleitamentoMaterno_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetAleitamentoMaterno() int64 {
	if !p.IsSetAleitamentoMaterno() {
		return FichaAtendimentoIndividualChildThrift_AleitamentoMaterno_DEFAULT
	}
	return *p.AleitamentoMaterno
}

var FichaAtendimentoIndividualChildThrift_DumDaGestante_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetDumDaGestante() int64 {
	if !p.IsSetDumDaGestante() {
		return FichaAtendimentoIndividualChildThrift_DumDaGestante_DEFAULT
	}
	return *p.DumDaGestante
}

var FichaAtendimentoIndividualChildThrift_IdadeGestacional_DEFAULT int32

func (p *FichaAtendimentoIndividualChildThrift) GetIdadeGestacional() int32 {
	if !p.IsSetIdadeGestacional() {
		return FichaAtendimentoIndividualChildThrift_IdadeGestacional_DEFAULT
	}
	return *p.IdadeGestacional
}

var FichaAtendimentoIndividualChildThrift_AtencaoDomiciliarModalidade_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetAtencaoDomiciliarModalidade() int64 {
	if !p.IsSetAtencaoDomiciliarModalidade() {
		return FichaAtendimentoIndividualChildThrift_AtencaoDomiciliarModalidade_DEFAULT
	}
	return *p.AtencaoDomiciliarModalidade
}

var FichaAtendimentoIndividualChildThrift_ProblemaCondicaoAvaliada_DEFAULT *ProblemaCondicaoAvaliacaoAIThrift

func (p *FichaAtendimentoIndividualChildThrift) GetProblemaCondicaoAvaliada() *ProblemaCondicaoAvaliacaoAIThrift {
	if !p.IsSetProblemaCondicaoAvaliada() {
		return FichaAtendimentoIndividualChildThrift_ProblemaCondicaoAvaliada_DEFAULT
	}
	return p.ProblemaCondicaoAvaliada
}

var FichaAtendimentoIndividualChildThrift_ExamesSolicitados_DEFAULT []string

func (p *FichaAtendimentoIndividualChildThrift) GetExamesSolicitados() []string {
	return p.ExamesSolicitados
}

var FichaAtendimentoIndividualChildThrift_ExamesAvaliados_DEFAULT []string

func (p *FichaAtendimentoIndividualChildThrift) GetExamesAvaliados() []string {
	return p.ExamesAvaliados
}

var FichaAtendimentoIndividualChildThrift_OutrosSia_DEFAULT []*OutrosSiaThrift

func (p *FichaAtendimentoIndividualChildThrift) GetOutrosSia() []*OutrosSiaThrift {
	return p.OutrosSia
}

var FichaAtendimentoIndividualChildThrift_VacinaEmDia_DEFAULT bool

func (p *FichaAtendimentoIndividualChildThrift) GetVacinaEmDia() bool {
	if !p.IsSetVacinaEmDia() {
		return FichaAtendimentoIndividualChildThrift_VacinaEmDia_DEFAULT
	}
	return *p.VacinaEmDia
}

var FichaAtendimentoIndividualChildThrift_Pic_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetPic() int64 {
	if !p.IsSetPic() {
		return FichaAtendimentoIndividualChildThrift_Pic_DEFAULT
	}
	return *p.Pic
}

var FichaAtendimentoIndividualChildThrift_FicouEmObservacao_DEFAULT bool

func (p *FichaAtendimentoIndividualChildThrift) GetFicouEmObservacao() bool {
	if !p.IsSetFicouEmObservacao() {
		return FichaAtendimentoIndividualChildThrift_FicouEmObservacao_DEFAULT
	}
	return *p.FicouEmObservacao
}

var FichaAtendimentoIndividualChildThrift_Nasfs_DEFAULT []int64

func (p *FichaAtendimentoIndividualChildThrift) GetNasfs() []int64 {
	return p.Nasfs
}

var FichaAtendimentoIndividualChildThrift_Condutas_DEFAULT []int64

func (p *FichaAtendimentoIndividualChildThrift) GetCondutas() []int64 {
	return p.Condutas
}

var FichaAtendimentoIndividualChildThrift_StGravidezPlanejada_DEFAULT bool

func (p *FichaAtendimentoIndividualChildThrift) GetStGravidezPlanejada() bool {
	if !p.IsSetStGravidezPlanejada() {
		return FichaAtendimentoIndividualChildThrift_StGravidezPlanejada_DEFAULT
	}
	return *p.StGravidezPlanejada
}

var FichaAtendimentoIndividualChildThrift_NuGestasPrevias_DEFAULT int32

func (p *FichaAtendimentoIndividualChildThrift) GetNuGestasPrevias() int32 {
	if !p.IsSetNuGestasPrevias() {
		return FichaAtendimentoIndividualChildThrift_NuGestasPrevias_DEFAULT
	}
	return *p.NuGestasPrevias
}

var FichaAtendimentoIndividualChildThrift_NuPartos_DEFAULT int32

func (p *FichaAtendimentoIndividualChildThrift) GetNuPartos() int32 {
	if !p.IsSetNuPartos() {
		return FichaAtendimentoIndividualChildThrift_NuPartos_DEFAULT
	}
	return *p.NuPartos
}

var FichaAtendimentoIndividualChildThrift_RacionalidadeSaude_DEFAULT int64

func (p *FichaAtendimentoIndividualChildThrift) GetRacionalidadeSaude() int64 {
	if !p.IsSetRacionalidadeSaude() {
		return FichaAtendimentoIndividualChildThrift_RacionalidadeSaude_DEFAULT
	}
	return *p.RacionalidadeSaude
}

var FichaAtendimentoIndividualChildThrift_PerimetroCefalico_DEFAULT float64

func (p *FichaAtendimentoIndividualChildThrift) GetPerimetroCefalico() float64 {
	if !p.IsSetPerimetroCefalico() {
		return FichaAtendimentoIndividualChildThrift_PerimetroCefalico_DEFAULT
	}
	return *p.PerimetroCefalico
}
func (p *FichaAtendimentoIndividualChildThrift) IsSetNumeroProntuario() bool {
	return p.NumeroProntuario != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetCns() bool {
	return p.Cns != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetDataNascimento() bool {
	return p.DataNascimento != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetLocalDeAtendimento() bool {
	return p.LocalDeAtendimento != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetSexo() bool {
	return p.Sexo != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetTurno() bool {
	return p.Turno != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetTipoAtendimento() bool {
	return p.TipoAtendimento != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetPesoAcompanhamentoNutricional() bool {
	return p.PesoAcompanhamentoNutricional != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetAlturaAcompanhamentoNutricional() bool {
	return p.AlturaAcompanhamentoNutricional != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetAleitamentoMaterno() bool {
	return p.AleitamentoMaterno != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetDumDaGestante() bool {
	return p.DumDaGestante != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetIdadeGestacional() bool {
	return p.IdadeGestacional != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetAtencaoDomiciliarModalidade() bool {
	return p.AtencaoDomiciliarModalidade != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetProblemaCondicaoAvaliada() bool {
	return p.ProblemaCondicaoAvaliada != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetExamesSolicitados() bool {
	return p.ExamesSolicitados != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetExamesAvaliados() bool {
	return p.ExamesAvaliados != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetOutrosSia() bool {
	return p.OutrosSia != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetVacinaEmDia() bool {
	return p.VacinaEmDia != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetPic() bool {
	return p.Pic != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetFicouEmObservacao() bool {
	return p.FicouEmObservacao != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetNasfs() bool {
	return p.Nasfs != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetCondutas() bool {
	return p.Condutas != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetStGravidezPlanejada() bool {
	return p.StGravidezPlanejada != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetNuGestasPrevias() bool {
	return p.NuGestasPrevias != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetNuPartos() bool {
	return p.NuPartos != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetRacionalidadeSaude() bool {
	return p.RacionalidadeSaude != nil
}

func (p *FichaAtendimentoIndividualChildThrift) IsSetPerimetroCefalico() bool {
	return p.PerimetroCefalico != nil
}

func (p *FichaAtendimentoIndividualChildThrift) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		case 8:
			if err := p.ReadField8(iprot); err != nil {
				return err
			}
		case 9:
			if err := p.ReadField9(iprot); err != nil {
				return err
			}
		case 10:
			if err := p.ReadField10(iprot); err != nil {
				return err
			}
		case 11:
			if err := p.ReadField11(iprot); err != nil {
				return err
			}
		case 12:
			if err := p.ReadField12(iprot); err != nil {
				return err
			}
		case 13:
			if err := p.ReadField13(iprot); err != nil {
				return err
			}
		case 14:
			if err := p.ReadField14(iprot); err != nil {
				return err
			}
		case 15:
			if err := p.ReadField15(iprot); err != nil {
				return err
			}
		case 16:
			if err := p.ReadField16(iprot); err != nil {
				return err
			}
		case 17:
			if err := p.ReadField17(iprot); err != nil {
				return err
			}
		case 18:
			if err := p.ReadField18(iprot); err != nil {
				return err
			}
		case 19:
			if err := p.ReadField19(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.ReadField20(iprot); err != nil {
				return err
			}
		case 21:
			if err := p.ReadField21(iprot); err != nil {
				return err
			}
		case 22:
			if err := p.ReadField22(iprot); err != nil {
				return err
			}
		case 23:
			if err := p.ReadField23(iprot); err != nil {
				return err
			}
		case 24:
			if err := p.ReadField24(iprot); err != nil {
				return err
			}
		case 25:
			if err := p.ReadField25(iprot); err != nil {
				return err
			}
		case 26:
			if err := p.ReadField26(iprot); err != nil {
				return err
			}
		case 27:
			if err := p.ReadField27(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.NumeroProntuario = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.Cns = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.DataNascimento = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.LocalDeAtendimento = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.Sexo = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 6: %s", err)
	} else {
		p.Turno = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField7(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 7: %s", err)
	} else {
		p.TipoAtendimento = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField8(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return fmt.Errorf("error reading field 8: %s", err)
	} else {
		p.PesoAcompanhamentoNutricional = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField9(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return fmt.Errorf("error reading field 9: %s", err)
	} else {
		p.AlturaAcompanhamentoNutricional = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 10: %s", err)
	} else {
		p.AleitamentoMaterno = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField11(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 11: %s", err)
	} else {
		p.DumDaGestante = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField12(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 12: %s", err)
	} else {
		p.IdadeGestacional = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField13(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 13: %s", err)
	} else {
		p.AtencaoDomiciliarModalidade = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField14(iprot thrift.TProtocol) error {
	p.ProblemaCondicaoAvaliada = &ProblemaCondicaoAvaliacaoAIThrift{}
	if err := p.ProblemaCondicaoAvaliada.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.ProblemaCondicaoAvaliada, err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField15(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]string, 0, size)
	p.ExamesSolicitados = tSlice
	for i := 0; i < size; i++ {
		var _elem2 string
		if v, err := iprot.ReadString(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem2 = v
		}
		p.ExamesSolicitados = append(p.ExamesSolicitados, _elem2)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField16(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]string, 0, size)
	p.ExamesAvaliados = tSlice
	for i := 0; i < size; i++ {
		var _elem3 string
		if v, err := iprot.ReadString(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem3 = v
		}
		p.ExamesAvaliados = append(p.ExamesAvaliados, _elem3)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField17(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]*OutrosSiaThrift, 0, size)
	p.OutrosSia = tSlice
	for i := 0; i < size; i++ {
		_elem4 := &OutrosSiaThrift{}
		if err := _elem4.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _elem4, err)
		}
		p.OutrosSia = append(p.OutrosSia, _elem4)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField18(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 18: %s", err)
	} else {
		p.VacinaEmDia = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField19(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 19: %s", err)
	} else {
		p.Pic = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 20: %s", err)
	} else {
		p.FicouEmObservacao = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField21(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]int64, 0, size)
	p.Nasfs = tSlice
	for i := 0; i < size; i++ {
		var _elem5 int64
		if v, err := iprot.ReadI64(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem5 = v
		}
		p.Nasfs = append(p.Nasfs, _elem5)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField22(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]int64, 0, size)
	p.Condutas = tSlice
	for i := 0; i < size; i++ {
		var _elem6 int64
		if v, err := iprot.ReadI64(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem6 = v
		}
		p.Condutas = append(p.Condutas, _elem6)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField23(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 23: %s", err)
	} else {
		p.StGravidezPlanejada = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField24(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 24: %s", err)
	} else {
		p.NuGestasPrevias = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField25(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 25: %s", err)
	} else {
		p.NuPartos = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField26(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 26: %s", err)
	} else {
		p.RacionalidadeSaude = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) ReadField27(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return fmt.Errorf("error reading field 27: %s", err)
	} else {
		p.PerimetroCefalico = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("FichaAtendimentoIndividualChildThrift"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := p.writeField8(oprot); err != nil {
		return err
	}
	if err := p.writeField9(oprot); err != nil {
		return err
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField11(oprot); err != nil {
		return err
	}
	if err := p.writeField12(oprot); err != nil {
		return err
	}
	if err := p.writeField13(oprot); err != nil {
		return err
	}
	if err := p.writeField14(oprot); err != nil {
		return err
	}
	if err := p.writeField15(oprot); err != nil {
		return err
	}
	if err := p.writeField16(oprot); err != nil {
		return err
	}
	if err := p.writeField17(oprot); err != nil {
		return err
	}
	if err := p.writeField18(oprot); err != nil {
		return err
	}
	if err := p.writeField19(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField21(oprot); err != nil {
		return err
	}
	if err := p.writeField22(oprot); err != nil {
		return err
	}
	if err := p.writeField23(oprot); err != nil {
		return err
	}
	if err := p.writeField24(oprot); err != nil {
		return err
	}
	if err := p.writeField25(oprot); err != nil {
		return err
	}
	if err := p.writeField26(oprot); err != nil {
		return err
	}
	if err := p.writeField27(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualChildThrift) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetNumeroProntuario() {
		if err := oprot.WriteFieldBegin("numeroProntuario", thrift.STRING, 1); err != nil {
			return fmt.Errorf("%T write field begin error 1:numeroProntuario: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.NumeroProntuario)); err != nil {
			return fmt.Errorf("%T.numeroProntuario (1) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 1:numeroProntuario: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetCns() {
		if err := oprot.WriteFieldBegin("cns", thrift.STRING, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:cns: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.Cns)); err != nil {
			return fmt.Errorf("%T.cns (2) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:cns: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetDataNascimento() {
		if err := oprot.WriteFieldBegin("dataNascimento", thrift.I64, 3); err != nil {
			return fmt.Errorf("%T write field begin error 3:dataNascimento: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.DataNascimento)); err != nil {
			return fmt.Errorf("%T.dataNascimento (3) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 3:dataNascimento: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetLocalDeAtendimento() {
		if err := oprot.WriteFieldBegin("localDeAtendimento", thrift.I64, 4); err != nil {
			return fmt.Errorf("%T write field begin error 4:localDeAtendimento: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.LocalDeAtendimento)); err != nil {
			return fmt.Errorf("%T.localDeAtendimento (4) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 4:localDeAtendimento: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetSexo() {
		if err := oprot.WriteFieldBegin("sexo", thrift.I64, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:sexo: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.Sexo)); err != nil {
			return fmt.Errorf("%T.sexo (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:sexo: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetTurno() {
		if err := oprot.WriteFieldBegin("turno", thrift.I64, 6); err != nil {
			return fmt.Errorf("%T write field begin error 6:turno: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.Turno)); err != nil {
			return fmt.Errorf("%T.turno (6) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 6:turno: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetTipoAtendimento() {
		if err := oprot.WriteFieldBegin("tipoAtendimento", thrift.I64, 7); err != nil {
			return fmt.Errorf("%T write field begin error 7:tipoAtendimento: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.TipoAtendimento)); err != nil {
			return fmt.Errorf("%T.tipoAtendimento (7) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 7:tipoAtendimento: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetPesoAcompanhamentoNutricional() {
		if err := oprot.WriteFieldBegin("pesoAcompanhamentoNutricional", thrift.DOUBLE, 8); err != nil {
			return fmt.Errorf("%T write field begin error 8:pesoAcompanhamentoNutricional: %s", p, err)
		}
		if err := oprot.WriteDouble(float64(*p.PesoAcompanhamentoNutricional)); err != nil {
			return fmt.Errorf("%T.pesoAcompanhamentoNutricional (8) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 8:pesoAcompanhamentoNutricional: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetAlturaAcompanhamentoNutricional() {
		if err := oprot.WriteFieldBegin("alturaAcompanhamentoNutricional", thrift.DOUBLE, 9); err != nil {
			return fmt.Errorf("%T write field begin error 9:alturaAcompanhamentoNutricional: %s", p, err)
		}
		if err := oprot.WriteDouble(float64(*p.AlturaAcompanhamentoNutricional)); err != nil {
			return fmt.Errorf("%T.alturaAcompanhamentoNutricional (9) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 9:alturaAcompanhamentoNutricional: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetAleitamentoMaterno() {
		if err := oprot.WriteFieldBegin("aleitamentoMaterno", thrift.I64, 10); err != nil {
			return fmt.Errorf("%T write field begin error 10:aleitamentoMaterno: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.AleitamentoMaterno)); err != nil {
			return fmt.Errorf("%T.aleitamentoMaterno (10) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 10:aleitamentoMaterno: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField11(oprot thrift.TProtocol) (err error) {
	if p.IsSetDumDaGestante() {
		if err := oprot.WriteFieldBegin("dumDaGestante", thrift.I64, 11); err != nil {
			return fmt.Errorf("%T write field begin error 11:dumDaGestante: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.DumDaGestante)); err != nil {
			return fmt.Errorf("%T.dumDaGestante (11) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 11:dumDaGestante: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField12(oprot thrift.TProtocol) (err error) {
	if p.IsSetIdadeGestacional() {
		if err := oprot.WriteFieldBegin("idadeGestacional", thrift.I32, 12); err != nil {
			return fmt.Errorf("%T write field begin error 12:idadeGestacional: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.IdadeGestacional)); err != nil {
			return fmt.Errorf("%T.idadeGestacional (12) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 12:idadeGestacional: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField13(oprot thrift.TProtocol) (err error) {
	if p.IsSetAtencaoDomiciliarModalidade() {
		if err := oprot.WriteFieldBegin("atencaoDomiciliarModalidade", thrift.I64, 13); err != nil {
			return fmt.Errorf("%T write field begin error 13:atencaoDomiciliarModalidade: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.AtencaoDomiciliarModalidade)); err != nil {
			return fmt.Errorf("%T.atencaoDomiciliarModalidade (13) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 13:atencaoDomiciliarModalidade: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField14(oprot thrift.TProtocol) (err error) {
	if p.IsSetProblemaCondicaoAvaliada() {
		if err := oprot.WriteFieldBegin("problemaCondicaoAvaliada", thrift.STRUCT, 14); err != nil {
			return fmt.Errorf("%T write field begin error 14:problemaCondicaoAvaliada: %s", p, err)
		}
		if err := p.ProblemaCondicaoAvaliada.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.ProblemaCondicaoAvaliada, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 14:problemaCondicaoAvaliada: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField15(oprot thrift.TProtocol) (err error) {
	if p.IsSetExamesSolicitados() {
		if err := oprot.WriteFieldBegin("examesSolicitados", thrift.LIST, 15); err != nil {
			return fmt.Errorf("%T write field begin error 15:examesSolicitados: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.ExamesSolicitados)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.ExamesSolicitados {
			if err := oprot.WriteString(string(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 15:examesSolicitados: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField16(oprot thrift.TProtocol) (err error) {
	if p.IsSetExamesAvaliados() {
		if err := oprot.WriteFieldBegin("examesAvaliados", thrift.LIST, 16); err != nil {
			return fmt.Errorf("%T write field begin error 16:examesAvaliados: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.STRING, len(p.ExamesAvaliados)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.ExamesAvaliados {
			if err := oprot.WriteString(string(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 16:examesAvaliados: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField17(oprot thrift.TProtocol) (err error) {
	if p.IsSetOutrosSia() {
		if err := oprot.WriteFieldBegin("outrosSia", thrift.LIST, 17); err != nil {
			return fmt.Errorf("%T write field begin error 17:outrosSia: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.OutrosSia)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.OutrosSia {
			if err := v.Write(oprot); err != nil {
				return fmt.Errorf("%T error writing struct: %s", v, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 17:outrosSia: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField18(oprot thrift.TProtocol) (err error) {
	if p.IsSetVacinaEmDia() {
		if err := oprot.WriteFieldBegin("vacinaEmDia", thrift.BOOL, 18); err != nil {
			return fmt.Errorf("%T write field begin error 18:vacinaEmDia: %s", p, err)
		}
		if err := oprot.WriteBool(bool(*p.VacinaEmDia)); err != nil {
			return fmt.Errorf("%T.vacinaEmDia (18) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 18:vacinaEmDia: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField19(oprot thrift.TProtocol) (err error) {
	if p.IsSetPic() {
		if err := oprot.WriteFieldBegin("pic", thrift.I64, 19); err != nil {
			return fmt.Errorf("%T write field begin error 19:pic: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.Pic)); err != nil {
			return fmt.Errorf("%T.pic (19) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 19:pic: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetFicouEmObservacao() {
		if err := oprot.WriteFieldBegin("ficouEmObservacao", thrift.BOOL, 20); err != nil {
			return fmt.Errorf("%T write field begin error 20:ficouEmObservacao: %s", p, err)
		}
		if err := oprot.WriteBool(bool(*p.FicouEmObservacao)); err != nil {
			return fmt.Errorf("%T.ficouEmObservacao (20) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 20:ficouEmObservacao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField21(oprot thrift.TProtocol) (err error) {
	if p.IsSetNasfs() {
		if err := oprot.WriteFieldBegin("nasfs", thrift.LIST, 21); err != nil {
			return fmt.Errorf("%T write field begin error 21:nasfs: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.Nasfs)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.Nasfs {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 21:nasfs: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField22(oprot thrift.TProtocol) (err error) {
	if p.IsSetCondutas() {
		if err := oprot.WriteFieldBegin("condutas", thrift.LIST, 22); err != nil {
			return fmt.Errorf("%T write field begin error 22:condutas: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.Condutas)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.Condutas {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 22:condutas: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField23(oprot thrift.TProtocol) (err error) {
	if p.IsSetStGravidezPlanejada() {
		if err := oprot.WriteFieldBegin("stGravidezPlanejada", thrift.BOOL, 23); err != nil {
			return fmt.Errorf("%T write field begin error 23:stGravidezPlanejada: %s", p, err)
		}
		if err := oprot.WriteBool(bool(*p.StGravidezPlanejada)); err != nil {
			return fmt.Errorf("%T.stGravidezPlanejada (23) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 23:stGravidezPlanejada: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField24(oprot thrift.TProtocol) (err error) {
	if p.IsSetNuGestasPrevias() {
		if err := oprot.WriteFieldBegin("nuGestasPrevias", thrift.I32, 24); err != nil {
			return fmt.Errorf("%T write field begin error 24:nuGestasPrevias: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.NuGestasPrevias)); err != nil {
			return fmt.Errorf("%T.nuGestasPrevias (24) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 24:nuGestasPrevias: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField25(oprot thrift.TProtocol) (err error) {
	if p.IsSetNuPartos() {
		if err := oprot.WriteFieldBegin("nuPartos", thrift.I32, 25); err != nil {
			return fmt.Errorf("%T write field begin error 25:nuPartos: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.NuPartos)); err != nil {
			return fmt.Errorf("%T.nuPartos (25) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 25:nuPartos: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField26(oprot thrift.TProtocol) (err error) {
	if p.IsSetRacionalidadeSaude() {
		if err := oprot.WriteFieldBegin("racionalidadeSaude", thrift.I64, 26); err != nil {
			return fmt.Errorf("%T write field begin error 26:racionalidadeSaude: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.RacionalidadeSaude)); err != nil {
			return fmt.Errorf("%T.racionalidadeSaude (26) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 26:racionalidadeSaude: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) writeField27(oprot thrift.TProtocol) (err error) {
	if p.IsSetPerimetroCefalico() {
		if err := oprot.WriteFieldBegin("perimetroCefalico", thrift.DOUBLE, 27); err != nil {
			return fmt.Errorf("%T write field begin error 27:perimetroCefalico: %s", p, err)
		}
		if err := oprot.WriteDouble(float64(*p.PerimetroCefalico)); err != nil {
			return fmt.Errorf("%T.perimetroCefalico (27) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 27:perimetroCefalico: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualChildThrift) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FichaAtendimentoIndividualChildThrift(%+v)", *p)
}

type FichaAtendimentoIndividualMasterThrift struct {
	HeaderTransport         *common.VariasLotacoesHeaderThrift       `thrift:"headerTransport,1" json:"headerTransport"`
	AtendimentosIndividuais []*FichaAtendimentoIndividualChildThrift `thrift:"atendimentosIndividuais,2" json:"atendimentosIndividuais"`
	UuidFicha               string                                   `thrift:"uuidFicha,3,required" json:"uuidFicha"`
	TpCdsOrigem             *int32                                   `thrift:"tpCdsOrigem,4" json:"tpCdsOrigem"`
}

func NewFichaAtendimentoIndividualMasterThrift() *FichaAtendimentoIndividualMasterThrift {
	return &FichaAtendimentoIndividualMasterThrift{}
}

var FichaAtendimentoIndividualMasterThrift_HeaderTransport_DEFAULT *common.VariasLotacoesHeaderThrift

func (p *FichaAtendimentoIndividualMasterThrift) GetHeaderTransport() *common.VariasLotacoesHeaderThrift {
	if !p.IsSetHeaderTransport() {
		return FichaAtendimentoIndividualMasterThrift_HeaderTransport_DEFAULT
	}
	return p.HeaderTransport
}

var FichaAtendimentoIndividualMasterThrift_AtendimentosIndividuais_DEFAULT []*FichaAtendimentoIndividualChildThrift

func (p *FichaAtendimentoIndividualMasterThrift) GetAtendimentosIndividuais() []*FichaAtendimentoIndividualChildThrift {
	return p.AtendimentosIndividuais
}

func (p *FichaAtendimentoIndividualMasterThrift) GetUuidFicha() string {
	return p.UuidFicha
}

var FichaAtendimentoIndividualMasterThrift_TpCdsOrigem_DEFAULT int32

func (p *FichaAtendimentoIndividualMasterThrift) GetTpCdsOrigem() int32 {
	if !p.IsSetTpCdsOrigem() {
		return FichaAtendimentoIndividualMasterThrift_TpCdsOrigem_DEFAULT
	}
	return *p.TpCdsOrigem
}
func (p *FichaAtendimentoIndividualMasterThrift) IsSetHeaderTransport() bool {
	return p.HeaderTransport != nil
}

func (p *FichaAtendimentoIndividualMasterThrift) IsSetAtendimentosIndividuais() bool {
	return p.AtendimentosIndividuais != nil
}

func (p *FichaAtendimentoIndividualMasterThrift) IsSetTpCdsOrigem() bool {
	return p.TpCdsOrigem != nil
}

func (p *FichaAtendimentoIndividualMasterThrift) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualMasterThrift) ReadField1(iprot thrift.TProtocol) error {
	p.HeaderTransport = &common.VariasLotacoesHeaderThrift{}
	if err := p.HeaderTransport.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.HeaderTransport, err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualMasterThrift) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]*FichaAtendimentoIndividualChildThrift, 0, size)
	p.AtendimentosIndividuais = tSlice
	for i := 0; i < size; i++ {
		_elem7 := &FichaAtendimentoIndividualChildThrift{}
		if err := _elem7.Read(iprot); err != nil {
			return fmt.Errorf("%T error reading struct: %s", _elem7, err)
		}
		p.AtendimentosIndividuais = append(p.AtendimentosIndividuais, _elem7)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualMasterThrift) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.UuidFicha = v
	}
	return nil
}

func (p *FichaAtendimentoIndividualMasterThrift) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.TpCdsOrigem = &v
	}
	return nil
}

func (p *FichaAtendimentoIndividualMasterThrift) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("FichaAtendimentoIndividualMasterThrift"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *FichaAtendimentoIndividualMasterThrift) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetHeaderTransport() {
		if err := oprot.WriteFieldBegin("headerTransport", thrift.STRUCT, 1); err != nil {
			return fmt.Errorf("%T write field begin error 1:headerTransport: %s", p, err)
		}
		if err := p.HeaderTransport.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.HeaderTransport, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 1:headerTransport: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualMasterThrift) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetAtendimentosIndividuais() {
		if err := oprot.WriteFieldBegin("atendimentosIndividuais", thrift.LIST, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:atendimentosIndividuais: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.STRUCT, len(p.AtendimentosIndividuais)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.AtendimentosIndividuais {
			if err := v.Write(oprot); err != nil {
				return fmt.Errorf("%T error writing struct: %s", v, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:atendimentosIndividuais: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualMasterThrift) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("uuidFicha", thrift.STRING, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:uuidFicha: %s", p, err)
	}
	if err := oprot.WriteString(string(p.UuidFicha)); err != nil {
		return fmt.Errorf("%T.uuidFicha (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:uuidFicha: %s", p, err)
	}
	return err
}

func (p *FichaAtendimentoIndividualMasterThrift) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetTpCdsOrigem() {
		if err := oprot.WriteFieldBegin("tpCdsOrigem", thrift.I32, 4); err != nil {
			return fmt.Errorf("%T write field begin error 4:tpCdsOrigem: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.TpCdsOrigem)); err != nil {
			return fmt.Errorf("%T.tpCdsOrigem (4) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 4:tpCdsOrigem: %s", p, err)
		}
	}
	return err
}

func (p *FichaAtendimentoIndividualMasterThrift) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FichaAtendimentoIndividualMasterThrift(%+v)", *p)
}
