/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace br.gov.saude.esusab.ras.atendprocedimentos
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class FichaProcedimentoChildThrift : TBase
  {
    private string _numProntuario;
    private string _cnsCidadao;
    private long _dtNascimento;
    private long _sexo;
    private long _localAtendimento;
    private long _turno;
    private bool _statusEscutaInicialOrientacao;
    private List<string> _procedimentos;
    private List<string> _outrosSiaProcedimentos;

    public string NumProntuario
    {
      get
      {
        return _numProntuario;
      }
      set
      {
        __isset.numProntuario = true;
        this._numProntuario = value;
      }
    }

    public string CnsCidadao
    {
      get
      {
        return _cnsCidadao;
      }
      set
      {
        __isset.cnsCidadao = true;
        this._cnsCidadao = value;
      }
    }

    public long DtNascimento
    {
      get
      {
        return _dtNascimento;
      }
      set
      {
        __isset.dtNascimento = true;
        this._dtNascimento = value;
      }
    }

    public long Sexo
    {
      get
      {
        return _sexo;
      }
      set
      {
        __isset.sexo = true;
        this._sexo = value;
      }
    }

    public long LocalAtendimento
    {
      get
      {
        return _localAtendimento;
      }
      set
      {
        __isset.localAtendimento = true;
        this._localAtendimento = value;
      }
    }

    public long Turno
    {
      get
      {
        return _turno;
      }
      set
      {
        __isset.turno = true;
        this._turno = value;
      }
    }

    public bool StatusEscutaInicialOrientacao
    {
      get
      {
        return _statusEscutaInicialOrientacao;
      }
      set
      {
        __isset.statusEscutaInicialOrientacao = true;
        this._statusEscutaInicialOrientacao = value;
      }
    }

    public List<string> Procedimentos
    {
      get
      {
        return _procedimentos;
      }
      set
      {
        __isset.procedimentos = true;
        this._procedimentos = value;
      }
    }

    public List<string> OutrosSiaProcedimentos
    {
      get
      {
        return _outrosSiaProcedimentos;
      }
      set
      {
        __isset.outrosSiaProcedimentos = true;
        this._outrosSiaProcedimentos = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool numProntuario;
      public bool cnsCidadao;
      public bool dtNascimento;
      public bool sexo;
      public bool localAtendimento;
      public bool turno;
      public bool statusEscutaInicialOrientacao;
      public bool procedimentos;
      public bool outrosSiaProcedimentos;
    }

    public FichaProcedimentoChildThrift() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              NumProntuario = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              CnsCidadao = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I64) {
              DtNascimento = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I64) {
              Sexo = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I64) {
              LocalAtendimento = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I64) {
              Turno = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.Bool) {
              StatusEscutaInicialOrientacao = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 8:
            if (field.Type == TType.List) {
              {
                Procedimentos = new List<string>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  string _elem2;
                  _elem2 = iprot.ReadString();
                  Procedimentos.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 9:
            if (field.Type == TType.List) {
              {
                OutrosSiaProcedimentos = new List<string>();
                TList _list3 = iprot.ReadListBegin();
                for( int _i4 = 0; _i4 < _list3.Count; ++_i4)
                {
                  string _elem5;
                  _elem5 = iprot.ReadString();
                  OutrosSiaProcedimentos.Add(_elem5);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("FichaProcedimentoChildThrift");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (NumProntuario != null && __isset.numProntuario) {
        field.Name = "numProntuario";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(NumProntuario);
        oprot.WriteFieldEnd();
      }
      if (CnsCidadao != null && __isset.cnsCidadao) {
        field.Name = "cnsCidadao";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(CnsCidadao);
        oprot.WriteFieldEnd();
      }
      if (__isset.dtNascimento) {
        field.Name = "dtNascimento";
        field.Type = TType.I64;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(DtNascimento);
        oprot.WriteFieldEnd();
      }
      if (__isset.sexo) {
        field.Name = "sexo";
        field.Type = TType.I64;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Sexo);
        oprot.WriteFieldEnd();
      }
      if (__isset.localAtendimento) {
        field.Name = "localAtendimento";
        field.Type = TType.I64;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(LocalAtendimento);
        oprot.WriteFieldEnd();
      }
      if (__isset.turno) {
        field.Name = "turno";
        field.Type = TType.I64;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Turno);
        oprot.WriteFieldEnd();
      }
      if (__isset.statusEscutaInicialOrientacao) {
        field.Name = "statusEscutaInicialOrientacao";
        field.Type = TType.Bool;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(StatusEscutaInicialOrientacao);
        oprot.WriteFieldEnd();
      }
      if (Procedimentos != null && __isset.procedimentos) {
        field.Name = "procedimentos";
        field.Type = TType.List;
        field.ID = 8;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Procedimentos.Count));
          foreach (string _iter6 in Procedimentos)
          {
            oprot.WriteString(_iter6);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (OutrosSiaProcedimentos != null && __isset.outrosSiaProcedimentos) {
        field.Name = "outrosSiaProcedimentos";
        field.Type = TType.List;
        field.ID = 9;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, OutrosSiaProcedimentos.Count));
          foreach (string _iter7 in OutrosSiaProcedimentos)
          {
            oprot.WriteString(_iter7);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("FichaProcedimentoChildThrift(");
      bool __first = true;
      if (NumProntuario != null && __isset.numProntuario) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NumProntuario: ");
        __sb.Append(NumProntuario);
      }
      if (CnsCidadao != null && __isset.cnsCidadao) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("CnsCidadao: ");
        __sb.Append(CnsCidadao);
      }
      if (__isset.dtNascimento) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DtNascimento: ");
        __sb.Append(DtNascimento);
      }
      if (__isset.sexo) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Sexo: ");
        __sb.Append(Sexo);
      }
      if (__isset.localAtendimento) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LocalAtendimento: ");
        __sb.Append(LocalAtendimento);
      }
      if (__isset.turno) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Turno: ");
        __sb.Append(Turno);
      }
      if (__isset.statusEscutaInicialOrientacao) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("StatusEscutaInicialOrientacao: ");
        __sb.Append(StatusEscutaInicialOrientacao);
      }
      if (Procedimentos != null && __isset.procedimentos) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Procedimentos: ");
        __sb.Append(Procedimentos);
      }
      if (OutrosSiaProcedimentos != null && __isset.outrosSiaProcedimentos) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OutrosSiaProcedimentos: ");
        __sb.Append(OutrosSiaProcedimentos);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
