// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package avaliacaoelegibilidade

import (
	"br/gov/saude/esusab/ras/common"
	"bytes"
	"fmt"
	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = common.GoUnusedProtection__
var GoUnusedProtection__ int

type FichaAvaliacaoElegibilidadeThrift struct {
	UuidFicha   string `thrift:"uuidFicha,1,required" json:"uuidFicha"`
	TpCdsOrigem *int32 `thrift:"tpCdsOrigem,2" json:"tpCdsOrigem"`
	// unused field # 3
	CnsCidadao                    *string                                `thrift:"cnsCidadao,4" json:"cnsCidadao"`
	NomeCidadao                   *string                                `thrift:"nomeCidadao,5" json:"nomeCidadao"`
	NomeSocialCidadao             *string                                `thrift:"nomeSocialCidadao,6" json:"nomeSocialCidadao"`
	DataNascimentoCidadao         *int64                                 `thrift:"dataNascimentoCidadao,7" json:"dataNascimentoCidadao"`
	SexoCidadao                   *int64                                 `thrift:"sexoCidadao,8" json:"sexoCidadao"`
	RacaCorCidadao                *int64                                 `thrift:"racaCorCidadao,9" json:"racaCorCidadao"`
	NomeMaeCidadao                *string                                `thrift:"nomeMaeCidadao,10" json:"nomeMaeCidadao"`
	DesconheceNomeMae             *bool                                  `thrift:"desconheceNomeMae,11" json:"desconheceNomeMae"`
	CodigoIbgeMunicipioNascimento *string                                `thrift:"codigoIbgeMunicipioNascimento,12" json:"codigoIbgeMunicipioNascimento"`
	NacionalidadeCidadao          *int64                                 `thrift:"nacionalidadeCidadao,13" json:"nacionalidadeCidadao"`
	EmailCidadao                  *string                                `thrift:"emailCidadao,14" json:"emailCidadao"`
	NumeroNisPisPasep             *string                                `thrift:"numeroNisPisPasep,15" json:"numeroNisPisPasep"`
	Endereco                      *common.EnderecoLocalPermanenciaThrift `thrift:"endereco,16" json:"endereco"`
	AtencaoDomiciliarProcedencia  *int64                                 `thrift:"atencaoDomiciliarProcedencia,17" json:"atencaoDomiciliarProcedencia"`
	AtencaoDomiciliarModalidade   *int64                                 `thrift:"atencaoDomiciliarModalidade,18" json:"atencaoDomiciliarModalidade"`
	CondicoesAvaliadas            []int64                                `thrift:"condicoesAvaliadas,19" json:"condicoesAvaliadas"`
	Cid10Principal                *string                                `thrift:"cid10Principal,20" json:"cid10Principal"`
	Cid10SecundarioUm             *string                                `thrift:"cid10SecundarioUm,21" json:"cid10SecundarioUm"`
	Cid10SecundarioDois           *string                                `thrift:"cid10SecundarioDois,22" json:"cid10SecundarioDois"`
	ConclusaoDestinoElegivel      *int64                                 `thrift:"conclusaoDestinoElegivel,23" json:"conclusaoDestinoElegivel"`
	ConclusaoDestinoInelegivel    []int64                                `thrift:"conclusaoDestinoInelegivel,24" json:"conclusaoDestinoInelegivel"`
	CuidadorCidadao               *int64                                 `thrift:"cuidadorCidadao,25" json:"cuidadorCidadao"`
	Turno                         *int64                                 `thrift:"turno,26" json:"turno"`
	HeaderTransport               *common.VariasLotacoesHeaderThrift     `thrift:"headerTransport,27" json:"headerTransport"`
	NomePaiCidadao                *string                                `thrift:"nomePaiCidadao,28" json:"nomePaiCidadao"`
	DesconheceNomePai             *bool                                  `thrift:"desconheceNomePai,29" json:"desconheceNomePai"`
	DtNaturalizacao               *int64                                 `thrift:"dtNaturalizacao,30" json:"dtNaturalizacao"`
	PortariaNaturalizacao         *string                                `thrift:"portariaNaturalizacao,31" json:"portariaNaturalizacao"`
	DtEntradaBrasil               *int64                                 `thrift:"dtEntradaBrasil,32" json:"dtEntradaBrasil"`
	PaisNascimento                *int64                                 `thrift:"paisNascimento,33" json:"paisNascimento"`
	Etnia                         *int64                                 `thrift:"etnia,34" json:"etnia"`
	CnsCuidador                   *string                                `thrift:"cnsCuidador,35" json:"cnsCuidador"`
}

func NewFichaAvaliacaoElegibilidadeThrift() *FichaAvaliacaoElegibilidadeThrift {
	return &FichaAvaliacaoElegibilidadeThrift{}
}

func (p *FichaAvaliacaoElegibilidadeThrift) GetUuidFicha() string {
	return p.UuidFicha
}

var FichaAvaliacaoElegibilidadeThrift_TpCdsOrigem_DEFAULT int32

func (p *FichaAvaliacaoElegibilidadeThrift) GetTpCdsOrigem() int32 {
	if !p.IsSetTpCdsOrigem() {
		return FichaAvaliacaoElegibilidadeThrift_TpCdsOrigem_DEFAULT
	}
	return *p.TpCdsOrigem
}

var FichaAvaliacaoElegibilidadeThrift_CnsCidadao_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetCnsCidadao() string {
	if !p.IsSetCnsCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_CnsCidadao_DEFAULT
	}
	return *p.CnsCidadao
}

var FichaAvaliacaoElegibilidadeThrift_NomeCidadao_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetNomeCidadao() string {
	if !p.IsSetNomeCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_NomeCidadao_DEFAULT
	}
	return *p.NomeCidadao
}

var FichaAvaliacaoElegibilidadeThrift_NomeSocialCidadao_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetNomeSocialCidadao() string {
	if !p.IsSetNomeSocialCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_NomeSocialCidadao_DEFAULT
	}
	return *p.NomeSocialCidadao
}

var FichaAvaliacaoElegibilidadeThrift_DataNascimentoCidadao_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetDataNascimentoCidadao() int64 {
	if !p.IsSetDataNascimentoCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_DataNascimentoCidadao_DEFAULT
	}
	return *p.DataNascimentoCidadao
}

var FichaAvaliacaoElegibilidadeThrift_SexoCidadao_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetSexoCidadao() int64 {
	if !p.IsSetSexoCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_SexoCidadao_DEFAULT
	}
	return *p.SexoCidadao
}

var FichaAvaliacaoElegibilidadeThrift_RacaCorCidadao_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetRacaCorCidadao() int64 {
	if !p.IsSetRacaCorCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_RacaCorCidadao_DEFAULT
	}
	return *p.RacaCorCidadao
}

var FichaAvaliacaoElegibilidadeThrift_NomeMaeCidadao_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetNomeMaeCidadao() string {
	if !p.IsSetNomeMaeCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_NomeMaeCidadao_DEFAULT
	}
	return *p.NomeMaeCidadao
}

var FichaAvaliacaoElegibilidadeThrift_DesconheceNomeMae_DEFAULT bool

func (p *FichaAvaliacaoElegibilidadeThrift) GetDesconheceNomeMae() bool {
	if !p.IsSetDesconheceNomeMae() {
		return FichaAvaliacaoElegibilidadeThrift_DesconheceNomeMae_DEFAULT
	}
	return *p.DesconheceNomeMae
}

var FichaAvaliacaoElegibilidadeThrift_CodigoIbgeMunicipioNascimento_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetCodigoIbgeMunicipioNascimento() string {
	if !p.IsSetCodigoIbgeMunicipioNascimento() {
		return FichaAvaliacaoElegibilidadeThrift_CodigoIbgeMunicipioNascimento_DEFAULT
	}
	return *p.CodigoIbgeMunicipioNascimento
}

var FichaAvaliacaoElegibilidadeThrift_NacionalidadeCidadao_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetNacionalidadeCidadao() int64 {
	if !p.IsSetNacionalidadeCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_NacionalidadeCidadao_DEFAULT
	}
	return *p.NacionalidadeCidadao
}

var FichaAvaliacaoElegibilidadeThrift_EmailCidadao_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetEmailCidadao() string {
	if !p.IsSetEmailCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_EmailCidadao_DEFAULT
	}
	return *p.EmailCidadao
}

var FichaAvaliacaoElegibilidadeThrift_NumeroNisPisPasep_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetNumeroNisPisPasep() string {
	if !p.IsSetNumeroNisPisPasep() {
		return FichaAvaliacaoElegibilidadeThrift_NumeroNisPisPasep_DEFAULT
	}
	return *p.NumeroNisPisPasep
}

var FichaAvaliacaoElegibilidadeThrift_Endereco_DEFAULT *common.EnderecoLocalPermanenciaThrift

func (p *FichaAvaliacaoElegibilidadeThrift) GetEndereco() *common.EnderecoLocalPermanenciaThrift {
	if !p.IsSetEndereco() {
		return FichaAvaliacaoElegibilidadeThrift_Endereco_DEFAULT
	}
	return p.Endereco
}

var FichaAvaliacaoElegibilidadeThrift_AtencaoDomiciliarProcedencia_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetAtencaoDomiciliarProcedencia() int64 {
	if !p.IsSetAtencaoDomiciliarProcedencia() {
		return FichaAvaliacaoElegibilidadeThrift_AtencaoDomiciliarProcedencia_DEFAULT
	}
	return *p.AtencaoDomiciliarProcedencia
}

var FichaAvaliacaoElegibilidadeThrift_AtencaoDomiciliarModalidade_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetAtencaoDomiciliarModalidade() int64 {
	if !p.IsSetAtencaoDomiciliarModalidade() {
		return FichaAvaliacaoElegibilidadeThrift_AtencaoDomiciliarModalidade_DEFAULT
	}
	return *p.AtencaoDomiciliarModalidade
}

var FichaAvaliacaoElegibilidadeThrift_CondicoesAvaliadas_DEFAULT []int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetCondicoesAvaliadas() []int64 {
	return p.CondicoesAvaliadas
}

var FichaAvaliacaoElegibilidadeThrift_Cid10Principal_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetCid10Principal() string {
	if !p.IsSetCid10Principal() {
		return FichaAvaliacaoElegibilidadeThrift_Cid10Principal_DEFAULT
	}
	return *p.Cid10Principal
}

var FichaAvaliacaoElegibilidadeThrift_Cid10SecundarioUm_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetCid10SecundarioUm() string {
	if !p.IsSetCid10SecundarioUm() {
		return FichaAvaliacaoElegibilidadeThrift_Cid10SecundarioUm_DEFAULT
	}
	return *p.Cid10SecundarioUm
}

var FichaAvaliacaoElegibilidadeThrift_Cid10SecundarioDois_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetCid10SecundarioDois() string {
	if !p.IsSetCid10SecundarioDois() {
		return FichaAvaliacaoElegibilidadeThrift_Cid10SecundarioDois_DEFAULT
	}
	return *p.Cid10SecundarioDois
}

var FichaAvaliacaoElegibilidadeThrift_ConclusaoDestinoElegivel_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetConclusaoDestinoElegivel() int64 {
	if !p.IsSetConclusaoDestinoElegivel() {
		return FichaAvaliacaoElegibilidadeThrift_ConclusaoDestinoElegivel_DEFAULT
	}
	return *p.ConclusaoDestinoElegivel
}

var FichaAvaliacaoElegibilidadeThrift_ConclusaoDestinoInelegivel_DEFAULT []int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetConclusaoDestinoInelegivel() []int64 {
	return p.ConclusaoDestinoInelegivel
}

var FichaAvaliacaoElegibilidadeThrift_CuidadorCidadao_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetCuidadorCidadao() int64 {
	if !p.IsSetCuidadorCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_CuidadorCidadao_DEFAULT
	}
	return *p.CuidadorCidadao
}

var FichaAvaliacaoElegibilidadeThrift_Turno_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetTurno() int64 {
	if !p.IsSetTurno() {
		return FichaAvaliacaoElegibilidadeThrift_Turno_DEFAULT
	}
	return *p.Turno
}

var FichaAvaliacaoElegibilidadeThrift_HeaderTransport_DEFAULT *common.VariasLotacoesHeaderThrift

func (p *FichaAvaliacaoElegibilidadeThrift) GetHeaderTransport() *common.VariasLotacoesHeaderThrift {
	if !p.IsSetHeaderTransport() {
		return FichaAvaliacaoElegibilidadeThrift_HeaderTransport_DEFAULT
	}
	return p.HeaderTransport
}

var FichaAvaliacaoElegibilidadeThrift_NomePaiCidadao_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetNomePaiCidadao() string {
	if !p.IsSetNomePaiCidadao() {
		return FichaAvaliacaoElegibilidadeThrift_NomePaiCidadao_DEFAULT
	}
	return *p.NomePaiCidadao
}

var FichaAvaliacaoElegibilidadeThrift_DesconheceNomePai_DEFAULT bool

func (p *FichaAvaliacaoElegibilidadeThrift) GetDesconheceNomePai() bool {
	if !p.IsSetDesconheceNomePai() {
		return FichaAvaliacaoElegibilidadeThrift_DesconheceNomePai_DEFAULT
	}
	return *p.DesconheceNomePai
}

var FichaAvaliacaoElegibilidadeThrift_DtNaturalizacao_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetDtNaturalizacao() int64 {
	if !p.IsSetDtNaturalizacao() {
		return FichaAvaliacaoElegibilidadeThrift_DtNaturalizacao_DEFAULT
	}
	return *p.DtNaturalizacao
}

var FichaAvaliacaoElegibilidadeThrift_PortariaNaturalizacao_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetPortariaNaturalizacao() string {
	if !p.IsSetPortariaNaturalizacao() {
		return FichaAvaliacaoElegibilidadeThrift_PortariaNaturalizacao_DEFAULT
	}
	return *p.PortariaNaturalizacao
}

var FichaAvaliacaoElegibilidadeThrift_DtEntradaBrasil_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetDtEntradaBrasil() int64 {
	if !p.IsSetDtEntradaBrasil() {
		return FichaAvaliacaoElegibilidadeThrift_DtEntradaBrasil_DEFAULT
	}
	return *p.DtEntradaBrasil
}

var FichaAvaliacaoElegibilidadeThrift_PaisNascimento_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetPaisNascimento() int64 {
	if !p.IsSetPaisNascimento() {
		return FichaAvaliacaoElegibilidadeThrift_PaisNascimento_DEFAULT
	}
	return *p.PaisNascimento
}

var FichaAvaliacaoElegibilidadeThrift_Etnia_DEFAULT int64

func (p *FichaAvaliacaoElegibilidadeThrift) GetEtnia() int64 {
	if !p.IsSetEtnia() {
		return FichaAvaliacaoElegibilidadeThrift_Etnia_DEFAULT
	}
	return *p.Etnia
}

var FichaAvaliacaoElegibilidadeThrift_CnsCuidador_DEFAULT string

func (p *FichaAvaliacaoElegibilidadeThrift) GetCnsCuidador() string {
	if !p.IsSetCnsCuidador() {
		return FichaAvaliacaoElegibilidadeThrift_CnsCuidador_DEFAULT
	}
	return *p.CnsCuidador
}
func (p *FichaAvaliacaoElegibilidadeThrift) IsSetTpCdsOrigem() bool {
	return p.TpCdsOrigem != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCnsCidadao() bool {
	return p.CnsCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetNomeCidadao() bool {
	return p.NomeCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetNomeSocialCidadao() bool {
	return p.NomeSocialCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetDataNascimentoCidadao() bool {
	return p.DataNascimentoCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetSexoCidadao() bool {
	return p.SexoCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetRacaCorCidadao() bool {
	return p.RacaCorCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetNomeMaeCidadao() bool {
	return p.NomeMaeCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetDesconheceNomeMae() bool {
	return p.DesconheceNomeMae != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCodigoIbgeMunicipioNascimento() bool {
	return p.CodigoIbgeMunicipioNascimento != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetNacionalidadeCidadao() bool {
	return p.NacionalidadeCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetEmailCidadao() bool {
	return p.EmailCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetNumeroNisPisPasep() bool {
	return p.NumeroNisPisPasep != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetEndereco() bool {
	return p.Endereco != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetAtencaoDomiciliarProcedencia() bool {
	return p.AtencaoDomiciliarProcedencia != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetAtencaoDomiciliarModalidade() bool {
	return p.AtencaoDomiciliarModalidade != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCondicoesAvaliadas() bool {
	return p.CondicoesAvaliadas != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCid10Principal() bool {
	return p.Cid10Principal != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCid10SecundarioUm() bool {
	return p.Cid10SecundarioUm != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCid10SecundarioDois() bool {
	return p.Cid10SecundarioDois != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetConclusaoDestinoElegivel() bool {
	return p.ConclusaoDestinoElegivel != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetConclusaoDestinoInelegivel() bool {
	return p.ConclusaoDestinoInelegivel != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCuidadorCidadao() bool {
	return p.CuidadorCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetTurno() bool {
	return p.Turno != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetHeaderTransport() bool {
	return p.HeaderTransport != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetNomePaiCidadao() bool {
	return p.NomePaiCidadao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetDesconheceNomePai() bool {
	return p.DesconheceNomePai != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetDtNaturalizacao() bool {
	return p.DtNaturalizacao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetPortariaNaturalizacao() bool {
	return p.PortariaNaturalizacao != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetDtEntradaBrasil() bool {
	return p.DtEntradaBrasil != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetPaisNascimento() bool {
	return p.PaisNascimento != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetEtnia() bool {
	return p.Etnia != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) IsSetCnsCuidador() bool {
	return p.CnsCuidador != nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		case 5:
			if err := p.ReadField5(iprot); err != nil {
				return err
			}
		case 6:
			if err := p.ReadField6(iprot); err != nil {
				return err
			}
		case 7:
			if err := p.ReadField7(iprot); err != nil {
				return err
			}
		case 8:
			if err := p.ReadField8(iprot); err != nil {
				return err
			}
		case 9:
			if err := p.ReadField9(iprot); err != nil {
				return err
			}
		case 10:
			if err := p.ReadField10(iprot); err != nil {
				return err
			}
		case 11:
			if err := p.ReadField11(iprot); err != nil {
				return err
			}
		case 12:
			if err := p.ReadField12(iprot); err != nil {
				return err
			}
		case 13:
			if err := p.ReadField13(iprot); err != nil {
				return err
			}
		case 14:
			if err := p.ReadField14(iprot); err != nil {
				return err
			}
		case 15:
			if err := p.ReadField15(iprot); err != nil {
				return err
			}
		case 16:
			if err := p.ReadField16(iprot); err != nil {
				return err
			}
		case 17:
			if err := p.ReadField17(iprot); err != nil {
				return err
			}
		case 18:
			if err := p.ReadField18(iprot); err != nil {
				return err
			}
		case 19:
			if err := p.ReadField19(iprot); err != nil {
				return err
			}
		case 20:
			if err := p.ReadField20(iprot); err != nil {
				return err
			}
		case 21:
			if err := p.ReadField21(iprot); err != nil {
				return err
			}
		case 22:
			if err := p.ReadField22(iprot); err != nil {
				return err
			}
		case 23:
			if err := p.ReadField23(iprot); err != nil {
				return err
			}
		case 24:
			if err := p.ReadField24(iprot); err != nil {
				return err
			}
		case 25:
			if err := p.ReadField25(iprot); err != nil {
				return err
			}
		case 26:
			if err := p.ReadField26(iprot); err != nil {
				return err
			}
		case 27:
			if err := p.ReadField27(iprot); err != nil {
				return err
			}
		case 28:
			if err := p.ReadField28(iprot); err != nil {
				return err
			}
		case 29:
			if err := p.ReadField29(iprot); err != nil {
				return err
			}
		case 30:
			if err := p.ReadField30(iprot); err != nil {
				return err
			}
		case 31:
			if err := p.ReadField31(iprot); err != nil {
				return err
			}
		case 32:
			if err := p.ReadField32(iprot); err != nil {
				return err
			}
		case 33:
			if err := p.ReadField33(iprot); err != nil {
				return err
			}
		case 34:
			if err := p.ReadField34(iprot); err != nil {
				return err
			}
		case 35:
			if err := p.ReadField35(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.UuidFicha = v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.TpCdsOrigem = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.CnsCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 5: %s", err)
	} else {
		p.NomeCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField6(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 6: %s", err)
	} else {
		p.NomeSocialCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField7(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 7: %s", err)
	} else {
		p.DataNascimentoCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField8(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 8: %s", err)
	} else {
		p.SexoCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField9(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 9: %s", err)
	} else {
		p.RacaCorCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField10(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 10: %s", err)
	} else {
		p.NomeMaeCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField11(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 11: %s", err)
	} else {
		p.DesconheceNomeMae = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField12(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 12: %s", err)
	} else {
		p.CodigoIbgeMunicipioNascimento = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField13(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 13: %s", err)
	} else {
		p.NacionalidadeCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField14(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 14: %s", err)
	} else {
		p.EmailCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField15(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 15: %s", err)
	} else {
		p.NumeroNisPisPasep = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField16(iprot thrift.TProtocol) error {
	p.Endereco = &common.EnderecoLocalPermanenciaThrift{}
	if err := p.Endereco.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.Endereco, err)
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField17(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 17: %s", err)
	} else {
		p.AtencaoDomiciliarProcedencia = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField18(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 18: %s", err)
	} else {
		p.AtencaoDomiciliarModalidade = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField19(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]int64, 0, size)
	p.CondicoesAvaliadas = tSlice
	for i := 0; i < size; i++ {
		var _elem0 int64
		if v, err := iprot.ReadI64(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem0 = v
		}
		p.CondicoesAvaliadas = append(p.CondicoesAvaliadas, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField20(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 20: %s", err)
	} else {
		p.Cid10Principal = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField21(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 21: %s", err)
	} else {
		p.Cid10SecundarioUm = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField22(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 22: %s", err)
	} else {
		p.Cid10SecundarioDois = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField23(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 23: %s", err)
	} else {
		p.ConclusaoDestinoElegivel = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField24(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return fmt.Errorf("error reading list begin: %s", err)
	}
	tSlice := make([]int64, 0, size)
	p.ConclusaoDestinoInelegivel = tSlice
	for i := 0; i < size; i++ {
		var _elem1 int64
		if v, err := iprot.ReadI64(); err != nil {
			return fmt.Errorf("error reading field 0: %s", err)
		} else {
			_elem1 = v
		}
		p.ConclusaoDestinoInelegivel = append(p.ConclusaoDestinoInelegivel, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return fmt.Errorf("error reading list end: %s", err)
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField25(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 25: %s", err)
	} else {
		p.CuidadorCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField26(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 26: %s", err)
	} else {
		p.Turno = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField27(iprot thrift.TProtocol) error {
	p.HeaderTransport = &common.VariasLotacoesHeaderThrift{}
	if err := p.HeaderTransport.Read(iprot); err != nil {
		return fmt.Errorf("%T error reading struct: %s", p.HeaderTransport, err)
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField28(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 28: %s", err)
	} else {
		p.NomePaiCidadao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField29(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return fmt.Errorf("error reading field 29: %s", err)
	} else {
		p.DesconheceNomePai = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField30(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 30: %s", err)
	} else {
		p.DtNaturalizacao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField31(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 31: %s", err)
	} else {
		p.PortariaNaturalizacao = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField32(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 32: %s", err)
	} else {
		p.DtEntradaBrasil = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField33(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 33: %s", err)
	} else {
		p.PaisNascimento = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField34(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return fmt.Errorf("error reading field 34: %s", err)
	} else {
		p.Etnia = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) ReadField35(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 35: %s", err)
	} else {
		p.CnsCuidador = &v
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("FichaAvaliacaoElegibilidadeThrift"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := p.writeField5(oprot); err != nil {
		return err
	}
	if err := p.writeField6(oprot); err != nil {
		return err
	}
	if err := p.writeField7(oprot); err != nil {
		return err
	}
	if err := p.writeField8(oprot); err != nil {
		return err
	}
	if err := p.writeField9(oprot); err != nil {
		return err
	}
	if err := p.writeField10(oprot); err != nil {
		return err
	}
	if err := p.writeField11(oprot); err != nil {
		return err
	}
	if err := p.writeField12(oprot); err != nil {
		return err
	}
	if err := p.writeField13(oprot); err != nil {
		return err
	}
	if err := p.writeField14(oprot); err != nil {
		return err
	}
	if err := p.writeField15(oprot); err != nil {
		return err
	}
	if err := p.writeField16(oprot); err != nil {
		return err
	}
	if err := p.writeField17(oprot); err != nil {
		return err
	}
	if err := p.writeField18(oprot); err != nil {
		return err
	}
	if err := p.writeField19(oprot); err != nil {
		return err
	}
	if err := p.writeField20(oprot); err != nil {
		return err
	}
	if err := p.writeField21(oprot); err != nil {
		return err
	}
	if err := p.writeField22(oprot); err != nil {
		return err
	}
	if err := p.writeField23(oprot); err != nil {
		return err
	}
	if err := p.writeField24(oprot); err != nil {
		return err
	}
	if err := p.writeField25(oprot); err != nil {
		return err
	}
	if err := p.writeField26(oprot); err != nil {
		return err
	}
	if err := p.writeField27(oprot); err != nil {
		return err
	}
	if err := p.writeField28(oprot); err != nil {
		return err
	}
	if err := p.writeField29(oprot); err != nil {
		return err
	}
	if err := p.writeField30(oprot); err != nil {
		return err
	}
	if err := p.writeField31(oprot); err != nil {
		return err
	}
	if err := p.writeField32(oprot); err != nil {
		return err
	}
	if err := p.writeField33(oprot); err != nil {
		return err
	}
	if err := p.writeField34(oprot); err != nil {
		return err
	}
	if err := p.writeField35(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("uuidFicha", thrift.STRING, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:uuidFicha: %s", p, err)
	}
	if err := oprot.WriteString(string(p.UuidFicha)); err != nil {
		return fmt.Errorf("%T.uuidFicha (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:uuidFicha: %s", p, err)
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetTpCdsOrigem() {
		if err := oprot.WriteFieldBegin("tpCdsOrigem", thrift.I32, 2); err != nil {
			return fmt.Errorf("%T write field begin error 2:tpCdsOrigem: %s", p, err)
		}
		if err := oprot.WriteI32(int32(*p.TpCdsOrigem)); err != nil {
			return fmt.Errorf("%T.tpCdsOrigem (2) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 2:tpCdsOrigem: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCnsCidadao() {
		if err := oprot.WriteFieldBegin("cnsCidadao", thrift.STRING, 4); err != nil {
			return fmt.Errorf("%T write field begin error 4:cnsCidadao: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.CnsCidadao)); err != nil {
			return fmt.Errorf("%T.cnsCidadao (4) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 4:cnsCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetNomeCidadao() {
		if err := oprot.WriteFieldBegin("nomeCidadao", thrift.STRING, 5); err != nil {
			return fmt.Errorf("%T write field begin error 5:nomeCidadao: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.NomeCidadao)); err != nil {
			return fmt.Errorf("%T.nomeCidadao (5) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 5:nomeCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetNomeSocialCidadao() {
		if err := oprot.WriteFieldBegin("nomeSocialCidadao", thrift.STRING, 6); err != nil {
			return fmt.Errorf("%T write field begin error 6:nomeSocialCidadao: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.NomeSocialCidadao)); err != nil {
			return fmt.Errorf("%T.nomeSocialCidadao (6) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 6:nomeSocialCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetDataNascimentoCidadao() {
		if err := oprot.WriteFieldBegin("dataNascimentoCidadao", thrift.I64, 7); err != nil {
			return fmt.Errorf("%T write field begin error 7:dataNascimentoCidadao: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.DataNascimentoCidadao)); err != nil {
			return fmt.Errorf("%T.dataNascimentoCidadao (7) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 7:dataNascimentoCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetSexoCidadao() {
		if err := oprot.WriteFieldBegin("sexoCidadao", thrift.I64, 8); err != nil {
			return fmt.Errorf("%T write field begin error 8:sexoCidadao: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.SexoCidadao)); err != nil {
			return fmt.Errorf("%T.sexoCidadao (8) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 8:sexoCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField9(oprot thrift.TProtocol) (err error) {
	if p.IsSetRacaCorCidadao() {
		if err := oprot.WriteFieldBegin("racaCorCidadao", thrift.I64, 9); err != nil {
			return fmt.Errorf("%T write field begin error 9:racaCorCidadao: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.RacaCorCidadao)); err != nil {
			return fmt.Errorf("%T.racaCorCidadao (9) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 9:racaCorCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField10(oprot thrift.TProtocol) (err error) {
	if p.IsSetNomeMaeCidadao() {
		if err := oprot.WriteFieldBegin("nomeMaeCidadao", thrift.STRING, 10); err != nil {
			return fmt.Errorf("%T write field begin error 10:nomeMaeCidadao: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.NomeMaeCidadao)); err != nil {
			return fmt.Errorf("%T.nomeMaeCidadao (10) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 10:nomeMaeCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField11(oprot thrift.TProtocol) (err error) {
	if p.IsSetDesconheceNomeMae() {
		if err := oprot.WriteFieldBegin("desconheceNomeMae", thrift.BOOL, 11); err != nil {
			return fmt.Errorf("%T write field begin error 11:desconheceNomeMae: %s", p, err)
		}
		if err := oprot.WriteBool(bool(*p.DesconheceNomeMae)); err != nil {
			return fmt.Errorf("%T.desconheceNomeMae (11) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 11:desconheceNomeMae: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField12(oprot thrift.TProtocol) (err error) {
	if p.IsSetCodigoIbgeMunicipioNascimento() {
		if err := oprot.WriteFieldBegin("codigoIbgeMunicipioNascimento", thrift.STRING, 12); err != nil {
			return fmt.Errorf("%T write field begin error 12:codigoIbgeMunicipioNascimento: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.CodigoIbgeMunicipioNascimento)); err != nil {
			return fmt.Errorf("%T.codigoIbgeMunicipioNascimento (12) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 12:codigoIbgeMunicipioNascimento: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField13(oprot thrift.TProtocol) (err error) {
	if p.IsSetNacionalidadeCidadao() {
		if err := oprot.WriteFieldBegin("nacionalidadeCidadao", thrift.I64, 13); err != nil {
			return fmt.Errorf("%T write field begin error 13:nacionalidadeCidadao: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.NacionalidadeCidadao)); err != nil {
			return fmt.Errorf("%T.nacionalidadeCidadao (13) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 13:nacionalidadeCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField14(oprot thrift.TProtocol) (err error) {
	if p.IsSetEmailCidadao() {
		if err := oprot.WriteFieldBegin("emailCidadao", thrift.STRING, 14); err != nil {
			return fmt.Errorf("%T write field begin error 14:emailCidadao: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.EmailCidadao)); err != nil {
			return fmt.Errorf("%T.emailCidadao (14) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 14:emailCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField15(oprot thrift.TProtocol) (err error) {
	if p.IsSetNumeroNisPisPasep() {
		if err := oprot.WriteFieldBegin("numeroNisPisPasep", thrift.STRING, 15); err != nil {
			return fmt.Errorf("%T write field begin error 15:numeroNisPisPasep: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.NumeroNisPisPasep)); err != nil {
			return fmt.Errorf("%T.numeroNisPisPasep (15) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 15:numeroNisPisPasep: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField16(oprot thrift.TProtocol) (err error) {
	if p.IsSetEndereco() {
		if err := oprot.WriteFieldBegin("endereco", thrift.STRUCT, 16); err != nil {
			return fmt.Errorf("%T write field begin error 16:endereco: %s", p, err)
		}
		if err := p.Endereco.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.Endereco, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 16:endereco: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField17(oprot thrift.TProtocol) (err error) {
	if p.IsSetAtencaoDomiciliarProcedencia() {
		if err := oprot.WriteFieldBegin("atencaoDomiciliarProcedencia", thrift.I64, 17); err != nil {
			return fmt.Errorf("%T write field begin error 17:atencaoDomiciliarProcedencia: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.AtencaoDomiciliarProcedencia)); err != nil {
			return fmt.Errorf("%T.atencaoDomiciliarProcedencia (17) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 17:atencaoDomiciliarProcedencia: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField18(oprot thrift.TProtocol) (err error) {
	if p.IsSetAtencaoDomiciliarModalidade() {
		if err := oprot.WriteFieldBegin("atencaoDomiciliarModalidade", thrift.I64, 18); err != nil {
			return fmt.Errorf("%T write field begin error 18:atencaoDomiciliarModalidade: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.AtencaoDomiciliarModalidade)); err != nil {
			return fmt.Errorf("%T.atencaoDomiciliarModalidade (18) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 18:atencaoDomiciliarModalidade: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField19(oprot thrift.TProtocol) (err error) {
	if p.IsSetCondicoesAvaliadas() {
		if err := oprot.WriteFieldBegin("condicoesAvaliadas", thrift.LIST, 19); err != nil {
			return fmt.Errorf("%T write field begin error 19:condicoesAvaliadas: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.CondicoesAvaliadas)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.CondicoesAvaliadas {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 19:condicoesAvaliadas: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField20(oprot thrift.TProtocol) (err error) {
	if p.IsSetCid10Principal() {
		if err := oprot.WriteFieldBegin("cid10Principal", thrift.STRING, 20); err != nil {
			return fmt.Errorf("%T write field begin error 20:cid10Principal: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.Cid10Principal)); err != nil {
			return fmt.Errorf("%T.cid10Principal (20) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 20:cid10Principal: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField21(oprot thrift.TProtocol) (err error) {
	if p.IsSetCid10SecundarioUm() {
		if err := oprot.WriteFieldBegin("cid10SecundarioUm", thrift.STRING, 21); err != nil {
			return fmt.Errorf("%T write field begin error 21:cid10SecundarioUm: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.Cid10SecundarioUm)); err != nil {
			return fmt.Errorf("%T.cid10SecundarioUm (21) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 21:cid10SecundarioUm: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField22(oprot thrift.TProtocol) (err error) {
	if p.IsSetCid10SecundarioDois() {
		if err := oprot.WriteFieldBegin("cid10SecundarioDois", thrift.STRING, 22); err != nil {
			return fmt.Errorf("%T write field begin error 22:cid10SecundarioDois: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.Cid10SecundarioDois)); err != nil {
			return fmt.Errorf("%T.cid10SecundarioDois (22) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 22:cid10SecundarioDois: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField23(oprot thrift.TProtocol) (err error) {
	if p.IsSetConclusaoDestinoElegivel() {
		if err := oprot.WriteFieldBegin("conclusaoDestinoElegivel", thrift.I64, 23); err != nil {
			return fmt.Errorf("%T write field begin error 23:conclusaoDestinoElegivel: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.ConclusaoDestinoElegivel)); err != nil {
			return fmt.Errorf("%T.conclusaoDestinoElegivel (23) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 23:conclusaoDestinoElegivel: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField24(oprot thrift.TProtocol) (err error) {
	if p.IsSetConclusaoDestinoInelegivel() {
		if err := oprot.WriteFieldBegin("conclusaoDestinoInelegivel", thrift.LIST, 24); err != nil {
			return fmt.Errorf("%T write field begin error 24:conclusaoDestinoInelegivel: %s", p, err)
		}
		if err := oprot.WriteListBegin(thrift.I64, len(p.ConclusaoDestinoInelegivel)); err != nil {
			return fmt.Errorf("error writing list begin: %s", err)
		}
		for _, v := range p.ConclusaoDestinoInelegivel {
			if err := oprot.WriteI64(int64(v)); err != nil {
				return fmt.Errorf("%T. (0) field write error: %s", p, err)
			}
		}
		if err := oprot.WriteListEnd(); err != nil {
			return fmt.Errorf("error writing list end: %s", err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 24:conclusaoDestinoInelegivel: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField25(oprot thrift.TProtocol) (err error) {
	if p.IsSetCuidadorCidadao() {
		if err := oprot.WriteFieldBegin("cuidadorCidadao", thrift.I64, 25); err != nil {
			return fmt.Errorf("%T write field begin error 25:cuidadorCidadao: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.CuidadorCidadao)); err != nil {
			return fmt.Errorf("%T.cuidadorCidadao (25) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 25:cuidadorCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField26(oprot thrift.TProtocol) (err error) {
	if p.IsSetTurno() {
		if err := oprot.WriteFieldBegin("turno", thrift.I64, 26); err != nil {
			return fmt.Errorf("%T write field begin error 26:turno: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.Turno)); err != nil {
			return fmt.Errorf("%T.turno (26) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 26:turno: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField27(oprot thrift.TProtocol) (err error) {
	if p.IsSetHeaderTransport() {
		if err := oprot.WriteFieldBegin("headerTransport", thrift.STRUCT, 27); err != nil {
			return fmt.Errorf("%T write field begin error 27:headerTransport: %s", p, err)
		}
		if err := p.HeaderTransport.Write(oprot); err != nil {
			return fmt.Errorf("%T error writing struct: %s", p.HeaderTransport, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 27:headerTransport: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField28(oprot thrift.TProtocol) (err error) {
	if p.IsSetNomePaiCidadao() {
		if err := oprot.WriteFieldBegin("nomePaiCidadao", thrift.STRING, 28); err != nil {
			return fmt.Errorf("%T write field begin error 28:nomePaiCidadao: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.NomePaiCidadao)); err != nil {
			return fmt.Errorf("%T.nomePaiCidadao (28) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 28:nomePaiCidadao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField29(oprot thrift.TProtocol) (err error) {
	if p.IsSetDesconheceNomePai() {
		if err := oprot.WriteFieldBegin("desconheceNomePai", thrift.BOOL, 29); err != nil {
			return fmt.Errorf("%T write field begin error 29:desconheceNomePai: %s", p, err)
		}
		if err := oprot.WriteBool(bool(*p.DesconheceNomePai)); err != nil {
			return fmt.Errorf("%T.desconheceNomePai (29) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 29:desconheceNomePai: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField30(oprot thrift.TProtocol) (err error) {
	if p.IsSetDtNaturalizacao() {
		if err := oprot.WriteFieldBegin("dtNaturalizacao", thrift.I64, 30); err != nil {
			return fmt.Errorf("%T write field begin error 30:dtNaturalizacao: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.DtNaturalizacao)); err != nil {
			return fmt.Errorf("%T.dtNaturalizacao (30) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 30:dtNaturalizacao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField31(oprot thrift.TProtocol) (err error) {
	if p.IsSetPortariaNaturalizacao() {
		if err := oprot.WriteFieldBegin("portariaNaturalizacao", thrift.STRING, 31); err != nil {
			return fmt.Errorf("%T write field begin error 31:portariaNaturalizacao: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.PortariaNaturalizacao)); err != nil {
			return fmt.Errorf("%T.portariaNaturalizacao (31) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 31:portariaNaturalizacao: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField32(oprot thrift.TProtocol) (err error) {
	if p.IsSetDtEntradaBrasil() {
		if err := oprot.WriteFieldBegin("dtEntradaBrasil", thrift.I64, 32); err != nil {
			return fmt.Errorf("%T write field begin error 32:dtEntradaBrasil: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.DtEntradaBrasil)); err != nil {
			return fmt.Errorf("%T.dtEntradaBrasil (32) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 32:dtEntradaBrasil: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField33(oprot thrift.TProtocol) (err error) {
	if p.IsSetPaisNascimento() {
		if err := oprot.WriteFieldBegin("paisNascimento", thrift.I64, 33); err != nil {
			return fmt.Errorf("%T write field begin error 33:paisNascimento: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.PaisNascimento)); err != nil {
			return fmt.Errorf("%T.paisNascimento (33) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 33:paisNascimento: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField34(oprot thrift.TProtocol) (err error) {
	if p.IsSetEtnia() {
		if err := oprot.WriteFieldBegin("etnia", thrift.I64, 34); err != nil {
			return fmt.Errorf("%T write field begin error 34:etnia: %s", p, err)
		}
		if err := oprot.WriteI64(int64(*p.Etnia)); err != nil {
			return fmt.Errorf("%T.etnia (34) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 34:etnia: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) writeField35(oprot thrift.TProtocol) (err error) {
	if p.IsSetCnsCuidador() {
		if err := oprot.WriteFieldBegin("cnsCuidador", thrift.STRING, 35); err != nil {
			return fmt.Errorf("%T write field begin error 35:cnsCuidador: %s", p, err)
		}
		if err := oprot.WriteString(string(*p.CnsCuidador)); err != nil {
			return fmt.Errorf("%T.cnsCuidador (35) field write error: %s", p, err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return fmt.Errorf("%T write field end error 35:cnsCuidador: %s", p, err)
		}
	}
	return err
}

func (p *FichaAvaliacaoElegibilidadeThrift) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FichaAvaliacaoElegibilidadeThrift(%+v)", *p)
}
