/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace br.gov.saude.esusab.ras.consumoalimentar
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PerguntaQuestionarioCriancasComMaisDoisAnosThrift : TBase
  {
    private PerguntaCriancasComMaisDoisAnosEnumThrift _pergunta;
    private RespostaUnicaEscolhaEnumThrift _respostaUnicaEscolha;
    private List<RespostaMultiplaEscolhaEnumThrift> _respostaMultiplaEscolha;

    /// <summary>
    /// 
    /// <seealso cref="PerguntaCriancasComMaisDoisAnosEnumThrift"/>
    /// </summary>
    public PerguntaCriancasComMaisDoisAnosEnumThrift Pergunta
    {
      get
      {
        return _pergunta;
      }
      set
      {
        __isset.pergunta = true;
        this._pergunta = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="RespostaUnicaEscolhaEnumThrift"/>
    /// </summary>
    public RespostaUnicaEscolhaEnumThrift RespostaUnicaEscolha
    {
      get
      {
        return _respostaUnicaEscolha;
      }
      set
      {
        __isset.respostaUnicaEscolha = true;
        this._respostaUnicaEscolha = value;
      }
    }

    public List<RespostaMultiplaEscolhaEnumThrift> RespostaMultiplaEscolha
    {
      get
      {
        return _respostaMultiplaEscolha;
      }
      set
      {
        __isset.respostaMultiplaEscolha = true;
        this._respostaMultiplaEscolha = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool pergunta;
      public bool respostaUnicaEscolha;
      public bool respostaMultiplaEscolha;
    }

    public PerguntaQuestionarioCriancasComMaisDoisAnosThrift() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Pergunta = (PerguntaCriancasComMaisDoisAnosEnumThrift)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                RespostaUnicaEscolha = (RespostaUnicaEscolhaEnumThrift)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.List) {
                {
                  RespostaMultiplaEscolha = new List<RespostaMultiplaEscolhaEnumThrift>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    RespostaMultiplaEscolhaEnumThrift _elem2;
                    _elem2 = (RespostaMultiplaEscolhaEnumThrift)iprot.ReadI32();
                    RespostaMultiplaEscolha.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("PerguntaQuestionarioCriancasComMaisDoisAnosThrift");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.pergunta) {
          field.Name = "pergunta";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)Pergunta);
          oprot.WriteFieldEnd();
        }
        if (__isset.respostaUnicaEscolha) {
          field.Name = "respostaUnicaEscolha";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)RespostaUnicaEscolha);
          oprot.WriteFieldEnd();
        }
        if (RespostaMultiplaEscolha != null && __isset.respostaMultiplaEscolha) {
          field.Name = "respostaMultiplaEscolha";
          field.Type = TType.List;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.I32, RespostaMultiplaEscolha.Count));
            foreach (RespostaMultiplaEscolhaEnumThrift _iter3 in RespostaMultiplaEscolha)
            {
              oprot.WriteI32((int)_iter3);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("PerguntaQuestionarioCriancasComMaisDoisAnosThrift(");
      bool __first = true;
      if (__isset.pergunta) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Pergunta: ");
        __sb.Append(Pergunta);
      }
      if (__isset.respostaUnicaEscolha) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RespostaUnicaEscolha: ");
        __sb.Append(RespostaUnicaEscolha);
      }
      if (RespostaMultiplaEscolha != null && __isset.respostaMultiplaEscolha) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RespostaMultiplaEscolha: ");
        __sb.Append(RespostaMultiplaEscolha);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
