#
# Autogenerated by Thrift Compiler (0.9.2)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'ficha_atendimento_domiciliar_types'

module Br
  module Gov
    module Saude
      module Esusab
        module Ras
          module Atenddomiciliar
          end
        end
      end
    end
  end
end
